spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/mybatis
#    username: sa
#    password:

  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/test  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
# handlebars 로컬에서 테스트시 반영 위해 적용
handlebars:
  cache: false




# database
#spring.datasource.url: jdbc:mysql://host:port/dbname?characterEncoding=utf8
#spring.datasource.username: root
#spring.datasource.password: password
#spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis
mybatis:
  configuration:
    multiple-result-sets-enabled: true
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null:  varchar
    default-fetch-size: 500
  mapper-locations: /mybatis/mapper/*.xml
#  config-location: /mybatis-config.xml
  type-aliases-package: com.setin.sample.dto
